config/routes.rb
Rails.application.routes.draw do
  # Devises
  devise_for :users
	# Resources
  resources :users
  resources :cars, :path => '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :user
	has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Aucune annonce disponible à cette adresse"
      redirect_to cars_path
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:brand, :model, :mileage, :year, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :authenticate_user!
  
  def show
  end

  private
    def set_user
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Aucun utilisateur disponible à cette adresse"
      redirect_to cars_path
    end

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :brand, value: 'Marque:' %>
    <%= form.text_field :brand,
      class: 'form-control',
      placeholder: 'Ex: Ford',
      include_blank: false,
      required: true
    %>
  </div>

  <div class="mb-3">
    <%= form.label :model, value: 'Model:' %>
    <%= form.text_field :model, 
      class: 'form-control',
      placeholder: 'Ex: Mustang', 
      include_blank: false, 
      required: true
    %>
  </div>

  <div class="mb-3">
    <%= form.label :mileage, value: 'Kilométrage:' %>
    <%= form.text_field :mileage, 
      class: 'form-control',
      placeholder: 'Ex: 10000',
      type: 'number', 
      include_blank: false, 
      required: true
    %>
  </div>

  <div class="mb-3">
    <%= form.label :year %>
    <%= form.date_select :year, 
      { :order => [:year],
        :start_year => 1900,
        :end_year => 2020 
      }, 
      { :class => 'form-control', include_blank: false, required: true }
    %>
  </div>

  <div class="custom-file my-3">
    <%= form.file_field :image, class: 'custom-file-input', include_blank: false, required: true %>
    <%= form.label :image, class: 'custom-file-label', value: 'Choisissez une photo' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-info btn-block mt-3' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1 class="mb-4">Modification de l'annonce</h1>

<%= render 'form', car: @car %>

app/views/cars/index.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<h1 class="mb-5">Toutes les annonces</h1>

<div class="container">
  <div class="row">
    <% if @cars.length  != 0 %>
      <% @cars.each do |car| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag(car.image, class: 'card-img-top') %>
            <div class="card-body">
              <p class="card-text"><%= car.brand %></p>
              <div class="d-flex justify-content-between align-items-center row">
                <div class="col-9 text-left">
                  <% if current_user == car.user %>
                    <%= link_to 'Modifier', edit_car_path(car), class: 'btn btn-info btn-sm' %>
                    <%= link_to 'Supprimer', car, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Etes vous sur ?' } %>
                  <% end %>
                </div>
                <div class="col-3 text-right">
                  <%= link_to 'Voir', car, class: 'btn btn-sm' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h6>
        Aucune annonces
      </h6>
    <% end %>
</div>

app/views/cars/new.html.erb
<h1 class="mb-4">Nouvelle annonce</h1>

<%= render 'form', car: @car %>

app/views/cars/show.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<div class="container w-75 mt-5">
	<div class="text-center">
		<%= image_tag(@car.image, class: 'rounded', style:'width: 100%') %>
	</div>
	<div class="row">
		<h1 class="my-4 col">
			<%= @car.brand %> | <%= @car.model %>
		</h1>
		<h6 class="col text-right my-4 mx-2">
			<%= link_to 'Propiétaire', user_path(@car.user), class: 'text-info' %>
		</h6>
	</div>
	<div class="pl-2">		
		<p>
			Kilométrage: <%= @car.mileage %> Km
		</p>
		<p>
			Année de mise en circulation: <%= @car.year %>
		</p>
	</div>
	<div class="actions float-right mt-5">
		<%= link_to 'Modifier', edit_car_path(@car), class: 'btn btn-sm btn-info' %>
    <%= link_to 'Supprimer', @car, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Etes vous sur ?' } %>
	</div>
</div>

app/views/layouts/_nav.html.erb
<header>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-5">
	  <%= link_to 'Voitures', cars_path, class: 'navbar-brand' %>
	  <div class="collapse navbar-collapse">
	  	<% if user_signed_in? %>
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item" style="width: 200px">
		        <%= link_to 'Créer une annonce', new_car_path, class: 'nav-link' %>
		      </li>
		    </ul>
	  	<% end %>
	  </div>
	  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
      	<% if user_signed_in? %>
  				<%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
					<%= link_to 'Deconnexion', destroy_user_session_path, class: 'nav-link', method: :delete %>
      	<% else %>
	        <li class="nav-item">
	          <%= link_to 'Inscription', new_user_registration_path, class: "nav-link" %>
	        </li>
	        <li class="nav-item">
	          <%= link_to 'Connexion', new_user_session_path, class: "nav-link" %>
	        </li>
        <% end %>
      </ul>
    </div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestSeniorMedia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/nav' %>
    <div class="container mt-4">
      <%= yield %>     
    </div>
  </body>
</html>

app/views/users/show.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<div class="container w-75 mt-5">
	<h4>
		Adresse email: <%= @user.email %>
	</h4>
	<h4 class="mt-4">
		<% if current_user == @user %>
			Mes annonces:
		<% else %>
			Ces annonces:
		<% end %>
	</h4>
	<div>
		<ul>
			<% @user.cars.each do |car| %>
				<li>
					<%= link_to car.model, car_path(car) %>
				</li>
			<% end %>
	</ul>	
	</div>
</div>